### ISSUE TITLE
Ajout de commentaire

### ISSUE THREAD

**Issue by ddelpire** [EsupPortail/esup-stage#1]
Dans le fichier properties, il serait bien d'indiquer quel est le WS ciblé.

identifiant pour l'accès au web services référentiel --> cela correspond aux identifiants du WS esup-SIscol

**Comment by ssound** [comment]
Prise en compte de la demande en ajoutant "(esup-SIscol)" en commentaire des les fichiers properties.
Sera disponible à partir de la version 1.0.5
