### ISSUE TITLE
Impossible de sélectionner l'élément pédagogique et la formation onglet "étudiant"

### ISSUE THREAD

**Issue by MZ-UCA** [EsupPortail/esup-stage#120]
Bonjour, 

Dans certains cas, et j'ignore pourquoi :
Dans la partie, "choisissez le cadre du stage" nous n'avons l'"année d'inscription" et la "formation" qui s'affichent (et qui ne sont pas modifiables.), aucune possibilité pour sélectionner l'"élément pédagogique " ou "choisir une formation". 

![esup 1](https://github.com/EsupPortail/esup-stage/assets/162425446/bf5d20fd-0994-4043-b2e6-1642d4df3c26)

Est-ce que quelqu'un sait d'où cela viendrait ? 

Je vous remercie par avance. 
Marta Zaharenko : Université Clermont Auvergne

**Comment by DidierUCA** [comment]
Idem demande #85
