### ISSUE TITLE
Changement du type et de la langue de convention

### ISSUE THREAD

**Issue by yoannlecuyer** [EsupPortail/esup-stage#142]
Lorsqu'on revient sur une convention déjà enregistrée, on n'a plus la possibilité de modifier le type et la langue de la convention.
En effet, si on modifie ces infos et qu'on va sur le récapitulatif, l'info reste inchangée.

**Comment by DidierUCA** [comment]
Idem demande #129 ;-)

**Comment by yoannlecuyer** [comment]
Je vais commencer à regarder les autres issues et je clos celle ci :)
