### ISSUE TITLE
Transmission des noms et prénoms du tuteur et signataire vers ESUP Signature

### ISSUE THREAD

**Issue by yoannlecuyer** [EsupPortail/esup-stage#147]
Bonjour,
Lorsqu'on envoie à la signature la convention de stage vers ESUP-Signature, on ne transmet que le mail du tuteur et du signataire dans l'établissement d'accueil.
Il manque donc les noms et prénoms qui sont nécessaires au fonctionnement optimal d'ESUP Signature (cf copie d'écran
![image](https://github.com/EsupPortail/esup-stage/assets/2776544/d64874fd-4cad-40d6-8dd7-a94d7e3369a8)

**Comment by lwasy44** [comment]
Bonjour,
Cette demande est importante à Nantes Université également. Nous prévoyons un déploiement à grande échelle d'Esup Stage à la rentrée 24 et c'est assez pénalisant de ne pas accéder à l'identité des signataires extérieurs au SI.
Merci la prise en compte de cette demande.
Bonne journée.
Laurent Wasylyszyn

**Comment by yoannlecuyer** [comment]
Bonjour,
Claude, j'ai commencé à analyser le code et bien que la partie alimentation des metadatas semble indiquer les noms et prénoms, en plus du mail, la partie transmission vers ESUP-Signature semble moins clair.
Peux-tu m'indiquer si via le connecteur ESUP-Signature, les noms et prénoms sont bien fournis dans le circuit ? Si oui, sous quel forme ?
Ainsi, ça permettra de savoir si c'est coté ESUP-Stage ou ESUP-Signature qu'il faut finaliser cet issue.

**Comment by yoannlecuyer** [comment]
Bonjour Claude,
Après plus d'analyse, j'ai retrouvé la partie du code qui nous concerne dans la méthode upload de la classe org.esup_portail.esup_stage.webhook.esupsignature.service.WebhookService  : 

        MetadataDto metadataDto = content.getMetadata();
        List<String> recipients = metadataDto.getSignatory().stream().map(s -> s.getOrder() + "*" + s.getMail()).collect(Collectors.toList());

        MultipartBodyBuilder builder = new MultipartBodyBuilder();
        builder.part("multipartFiles", geMultipartFile(metadataDto.getTitle(), Base64.decode(content.getPdf64())));
        builder.part("createByEppn", "system");
        builder.part("recipientsEmails", String.join(",", recipients));

On constate qu'uniquement la liste des mails des destinataires, dans l'ordre indiqué est renseignée et envoyé sur ESUP-Signature et les noms et prénoms sont bien absents.
Au moins pour les entreprises, il faudrait indiquer nom et prénom.

**Comment by kaisersly** [comment]
Bonjour à tous,

en fait lorsque l'intégration ESUP-Stage <-> ESUP-Signature a été développée, ESUP-Signature ne proposait que de renseigner les adresses mail des destinataires. Ce qui faisait le lien ensuite dans l'application pour les utilisateurs locaux c'était le LDAP.

Depuis une des dernières versions d'ESUP-Signature, il est désormais possible de renseigner et le nom et le prénom d'un destinataire : https://github.com/EsupPortail/esup-signature/blob/b62199240fb85c08518c2f24c47169147944e70b/src/main/java/org/esupportail/esupsignature/web/ws/WorkflowWsController.java#L60

On pourrait donc adapter le code pour envoyer une charge utile qui fait apparaître ces champs.

En revanche, il faudra bien communiquer sur la version minimale d'ESUP-Signature nécessaire.

**Comment by yoannlecuyer** [comment]
Bonjour,
Merci pour cette info et effectivement, la version de ESUP-Signature risque d'être un élément contraignant à mettre en avant.
Claude, peux-tu nous dire si un patch peut être proposé avant le lot 3 ?

**Comment by lwasy44** [comment]
Bonjour,
Pour moi, corrigé en 2.1.8.
Vous pouvez fermer ce ticket.
Bonne journée.
Laurent (Nantes Université)

**Comment by yoannlecuyer** [comment]
Bonjour,
Effectivement, nous avons déployé la 2.1.8 en prod et cela a bien été résolu.
Je clos le ticket.
Cordialement
Yoann
