### ISSUE TITLE
Configuration de l’authentification

### ISSUE THREAD

**Issue by shiipou** [EsupPortail/esup-stage#15]

**Comment by vdubus** [comment]
Currently, the authentication is working using an Embedded LDPA.
It is possible to manage the authentication using CAS, but we need to setup an Embedded CAS server as we can't use our university CAS currently.

**Comment by vdubus** [comment]
The use of a CAS mock server could be the answer to develop the CAS authentication without access to the university CAS server.
Found a few clues there:

- https://github.com/soulwing/cas-mock-server
- https://github.com/veo-labs/cas-server-mock

**Comment by vdubus** [comment]
Putting the subject on stand by as I can't figure what is going wrong on the **cas-mock-server**.
I have create a ticket about my issue on their side: https://github.com/soulwing/cas-mock-server/issues/8

Currently, the filtering isn't yet fully functional: we have to figure out which URL can be available to all, and which can't.
I will enable the login using only the  embedded **ldap** for now.

**Comment by vdubus** [comment]
Create the container for "cas-mock-server":
```cmd
docker container run -dp 8085:8080 -e ATTRIBUTES_JSON_URL=http://localhost/json/cas.json  soulwing/cas-mock-server
```

CAS configuration added with pull-request #83.
