### ISSUE TITLE
Problème de chevauchement de 2 conventions

### ISSUE THREAD

**Issue by yoannlecuyer** [EsupPortail/esup-stage#169]
Bonjour,
Du fait qu'on ne peut pas modifier une convention validée et envoyée en signature, on s'expose à une problématique lors de la ressaisie de la convention.
En effet, si jamais, malgré de nombreuses vérifications, l'entreprise, l'enseignant ou le viseur refuse de signer la convention pour imposer une modification, la seule solution est de ressaisir la convention.
Le problème ici est que ESUP-Stage nous empêche de faire chevaucher 2 conventions.
Dans le cas d'usage standard, cela se comprend mais quand on doit ressaisir une convention, cela est bloquant pour les gestionnaires et les étudiants.

Une solution serait de permettre au gestionnaire de supprimer la convention si possible en créant une nouvelle convention (donc nouvelle id compatible avec la procédure de signature électronique) préremplie avec les infos de la précédente.

**Comment by csylvanie** [comment]
Bonjour Yoann,
Nous avons fait en sorte de respecter les directives en matière de signature électronique. Un document envoyé en signature électronique ne peut plus être modifié. Toute correction éventuelle ne peut se faire que par : 
- la création d'un avenant,
- la création d'une nouvelle convention,
- le retour à la gestion papier pour les conventions concernées
Par ailleurs, il n'y a aucun blocage pour les gestionnaires. Cela signifie que le gestionnaire peut recréer une convention à l'identique de la convention précédente. Le blocage n'existe que pour les étudiants afin d'éviter les cas de fraude. A titre d'exemple, à Dauphine le gestionnaire initialise la nouvelle convention en saisissant les informations minimum dont la date de début et de fin du stage. Il laisse ensuite l'étudiant finaliser sa convention.
