### ISSUE TITLE
Gestion des réponses CAS XML

### ISSUE THREAD

**Issue by kaisersly** [EsupPortail/esup-stage#184]
L'application en l'état ne gère que les réponses JSON du serveur CAS. Il faudrait permettre de gérer les réponses XML également.

Cette issue est semblable a une issue qui a déjà été marquée comme complétée :
https://github.com/EsupPortail/esup-stage/issues/4

**Comment by kaisersly** [comment]
PR correspondante : #202

**Comment by csylvanie** [comment]
Demande traitée et validée dans la version 2.1.9 de ESUP-Stage
