### ISSUE TITLE
Permettre d'utiliser les built-ins Freemarker dans les templates

### ISSUE THREAD

**Issue by kaisersly** [EsupPortail/esup-stage#201]
Freemarker permet d'ajouter des annotations pour modifier l'affichage d'un paramètre. Par exemple `${etudiant.nom?upper_case}` affiche le nom de l'étudiant en majuscules.

La fonction de contrôle des paramètres d'ESUP-Stage ne permet pas d'utiliser ce type de notation car elle vérifie le nom complet du paramètre `etudiant.nom?upper_case` et pas seulement `etudiant.nom`.

Voir https://freemarker.apache.org/docs/dgui_quickstart_template.html#autoid_7

**Comment by kaisersly** [comment]
PR correspondante : #203

**Comment by csylvanie** [comment]
Sera géré dans la prochaine release v2.1.9
