### ISSUE TITLE
Annuler l'ancien parapheur lors d'un nouvel envoi en signature (ESUP-Signature)

### ISSUE THREAD

**Issue by kaisersly** [EsupPortail/esup-stage#204]
Si une convention a déjà été envoyée pour signature dans ESUP-Signature, et qu'on procède à un nouvel envoi, l'ancien parapheur dans ESUP-Signature est toujours "En cours".
Dans ce cas, il faut que l'ancien parapheur soit mis à la corbeille.

**Comment by kaisersly** [comment]
PR correspondante : #205

**Comment by csylvanie** [comment]
Sera géré dans la prochaine release v2.1.9
