### ISSUE TITLE
Afficher la devise dans l'extraction

### ISSUE THREAD

**Issue by Florimond-Jouffroy** [EsupPortail/esup-stage#217]
Tout est dans le titre :
Nous avons besoin d'afficher la devise utiliser dans les exports des conventions.
Merci

**Comment by csylvanie** [comment]
Bonjour @Florimond-Jouffroy ,
Cette demande fait partie de l'amélioration de l'export Excel déjà prévu pour l'année 2025. Vous aurez la possibilité de personnaliser les colonnes de l'export. Je me permets donc de clôturer ce ticket.
