### ISSUE TITLE
Bug aléatoire : Tuteur pro/Signataire

### ISSUE THREAD

**Issue by CamilleULILLE** [EsupPortail/esup-stage#221]
Bonjour,

Nous avons de plus en plus de remontées du bug suivant : les champs de renseignements TUTEUR PRO et SIGNATAIRE sont renseignés correctement, mais sur la convention papier l'un est écrasé par l'autre (et parfois vice versa) au niveau des champs et des signatures.
Exemple : 
TUTEUR PRO = X
SIGNATAIRE = Y
Sur la convention papier au niveau des signatures : TUTEUR PRO et SIGNATAIRE = Y

Sera-t-il possible de corriger ce bug ?
Merci,
Bien à vous,
Camille ULille

**Comment by yoannlecuyer** [comment]
Bonjour,

Cette situation revient régulièrement chez nous mais il ne s'agit pas d'un bug mais plutot d'un problème d'ergonomie.
En effet, le problème initial est que l'étudiant, quand il crée sa convention, va utiliser la même fiche contact sur le tuteur pro et le signataire.
Aussi, lorsqu'on veut corriger les infos du contact, plutot que de créer un nouveau contact, l'étudiant ou le gestionnaire va Modifier la fiche contact et donc dans tous les cas, on aura toujours la même fiche qui sera à chaque fois modifiée.

Comme indiqué, et pour l'avoir testé avec mes gestionnaires (probablement trop habitués sur PStage), il n'est pas évident de cliquer sur Sélection du tuteur pro et le regard se porte directement sur Modifier car au final, c'est ce qu'on veut faire, modifier l'info
![image](https://github.com/user-attachments/assets/10979e11-40a1-413c-8b03-3283c4adbb63)

Il faudrait donc trouver un moyen de rendre l'interface de modification plus claire.

**Comment by csylvanie** [comment]
Cette demande rejoint la demande #220. Je me permets donc de clôturer le ticket et je vous invite à suivre l'évolution du ticket du collègue.
