### ISSUE TITLE
Suivi des signatures électroniques accessibles par les gestionnaires

### ISSUE THREAD

**Issue by lwasy44** [EsupPortail/esup-stage#224]
Bonjour,
Pourriez-vous permettre au gestionnaire d'accéder au suivi des signatures électroniques ?
Seuls les responsables gestionnaires et administrateurs ont accès à cette fonctionnalité.
Merci d'avance et bonne journée.
Laurent Wasylyszyn
Nantes Université.

**Comment by csylvanie** [comment]
Bonjour,
Cette demande est redondante avec le ticket #231. Je vais donc la clôturer.
