### ISSUE TITLE
Extraction des infos de stage sur un seul onglet

### ISSUE THREAD

**Issue by yoannlecuyer** [EsupPortail/esup-stage#233]
Bonjour,
Beaucoup de mes gestionnaires se plaignent d'avoir les infos extraites sur 2 onglets au lieu d'un seul.
Pour leur usage qui consiste à avoir toutes les infos réunies dans un seul fichier, cela nécessite un traitement inutile.
Pour rappel, dans PStage, les infos étaient dans un seul onglet.
Cordialement,

**Comment by CamilleULILLE** [comment]
Je plussoie, j'ai la même remontée des gestionnaires.

Camille ULille

**Comment by csylvanie** [comment]
Bonjour Yoann,
Cette demande figure dans le cahier des charges du lot 3. Il s'agira de remettre en place la fonctionnalité de Pstage permettant de choisir les colonnes qui figureront dans l'extraction Excel. Il n'y aura donc plus qu'un seul onglet avec les colonnes souhaitées. Je me permets donc de clôturer ce ticket. Il faudra suivre les communications à venir via Github ou la liste de diffusion pour savoir dans quelle version ce changement sera inclus. Je serai beaucoup plus précis durant le premier trimestre 2025.
