### ISSUE TITLE
Autoriser les étudiants à créer uniquement le service et contacts, mais pas la fiche signalétique de l'établissement d'accueil

### ISSUE THREAD

**Issue by lovatoe** [EsupPortail/esup-stage#234]
Bonjour,

Il est prévu que nos étudiants cherchent leur organisme d'accueil via le SIRET et que la fiche signalétique s'affiche déjà remplie car les données de l'API sirene seront déjà importées par notre service informatique.
On ne veut donc pas les autoriser à modifier cette base d'organismes qui possède des données fiables.
Par contre, on souhaiterait que les étudiants puissent créer le service d'accueil et les contacts.
Comment peut-on faire?

Eva Lovato 
Responsable des stages
Université Paris Cité

**Comment by csylvanie** [comment]
Bonjour Eva,
Cela sera pris en compte dans l'évolution portant sur l'amélioration de la saisie des entreprises d'accueil. Il s'agira effectivement d'utiliser l'API Sirene. Les étudiants auront toutefois la possibilité de créer le service d'accueil et le contact car ces informations ne sont pas données par l'API. Il faudra attendre l'implémentation de ces fonctionnalités qui sont prioritaires. Encore un peu de patience nous savons que cela est très attendu.
Je me permets de clôturer ce ticket. La fonctionnalité sera annoncée via la liste de diffusion (planning et date estimée de livraison).
