### ISSUE TITLE
Modification des infos entreprises

### ISSUE THREAD

**Issue by Salima-UL** [EsupPortail/esup-stage#235]
Bonjour,

en laissant les étudiants avoir le droit de création et modification des entreprises nous nous retrouvons avec des doublons a ne plus en finir (création avec le statut ONG) et des entreprises (dont l'université) qui change de raison social ou de statut. 
Nous avons décidé de ne plus donner le droit de création et modification aux étudiants. 

- Problème 1 : est-ce qu'il serait possible de découpler le droit de création et de modification des entreprises ? 
- Problème 2 : pour donner le droit aux gestionnaires de modifier le catalogue entreprise, je dois leur donner le droit à la table de nomenclature, ce qui n'est pas possible. Est-ce qu'il serait possible de découpler ce droit là aussi ? Car au final les gestionnaires doivent attendre que la convention ait un numéro pour agir dessus et modifier l'entreprise or si l'entreprise n'existe pas, cela bloque tout le processus. 
- Problème 3 : depuis que j'ai coupé ce droit de création/modification des entreprises j'ai des étudiants qui n'ont plus les droits pour saisir leur tuteur universitaire. Est-ce qu'il y a un lien ??

Merci pour votre aide, 
Salima ALAOUI
Université de Lorraine

**Comment by csylvanie** [comment]
Bonjour Salima,
Cette problématique sera traitée dans le cadre de l'évolution de la gestion de la saisie des entreprises d'accueil. Cette évolution sera l'un de nos chantiers prioritaires en début d'année 2025. De ce fait, nous ne pouvons pas entreprendre dans l'immédiat les modifications demandées car elles vont très vite être écrasées par les travaux à venir sur ce sujet. Nous pourrons en reparler lors du prochain atelier destiné à la priorisation des demandes.
Je me permets donc de clôturer le ticket.

**Comment by Salima-UL** [comment]
Bonjour, 

bien reçu, merci, 

Salima 

	[ https://www.univ-lorraine.fr/luniversite-de-lorraine/notre-ambition-europeenne-avec-eureca-pro/ ] 	

Avec Eureca-Pro, l'Université de Lorraine 
devient université européenne 

Salima ALAOUI 
Responsable du Pôle Scolarité Générale et Outils du SI 

Direction de la Formation 

Université de Lorraine 
91 avenue de la Libération 
54000 Nancy 
03 72 74 03 50 	

Retrouvez toute l'actualité de l'université sur [ http://factuel.univ-lorraine.fr/ ] 

Et suivez-nous sur les réseaux sociaux [ https://www.facebook.com/UnivLorraine ] [ https://www.linkedin.com/school/universit-de-lorraine/ ] [ https://www.instagram.com/univlorraine/ ] [ http://factuel.univ-lorraine.fr/feed//rss-articles.xml ]
