### ISSUE TITLE
Extraction recherche avancée

### ISSUE THREAD

**Issue by CamilleULILLE** [EsupPortail/esup-stage#236]
Bonjour,

Plusieurs de nos gestionnaires nous ont remonté leur difficultés d'analyse des extractions Esup-stage telle qu'elles se présentent actuellement.
En effet, le manque du bouton "recherche avancée" ne permet pas d'accéder à une sélection de critères variées pour des extractions précises.

Bien à vous,
Camille ULille

**Comment by csylvanie** [comment]
Bonjour Camille,

Il est prévu d'améliorer la possibilité de personnaliser l'extraction des données à partir de l'interface. Vous aurez la possiblité de choisir les colonnes à extraire. Je me permets donc de clôturer le ticket car cette demande figure dans le lot d'évolutions à traiter.
