### ISSUE TITLE
Problème CKEditor pour ESUP-Stage

### ISSUE THREAD

**Issue by csylvanie** [EsupPortail/esup-stage#239]
Bonjour Messieurs,

Je me permet de vous contacter au sujet de l'intégration d'ESUP-Stage.
Suite à une cyber attaque cet été, nous sommes en pleine reconstruction de notre SI et je reprend les travaux de migration de PStage vers ESUP-Stage au sein de l'Université Paris-Saclay.
Déjà avant la cyber attaque, j'avais eu des problèmes avec CKEditor lors de la compilation de ESUP-Stage (que l'on avait résolu avec un ingénieur système en passant par de l'intégration gitlab-ci et du docker). Aujourd'hui, le builder en ligne de CKEditor indiqué dans la documentation n'est plus accessible :  [https://ckeditor.com/ckeditor-5/online-builder/](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fckeditor.com%2Fckeditor-5%2Fonline-builder%2F&data=05%7C02%7Cclaude.sylvanie%40dauphine.psl.eu%7C7533be9e95a6403db33308dd1eac8fdb%7C81e7c4de26c94531b076b70e2d75966e%7C0%7C0%7C638700448682392191%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=HFxuEkYuHswznIvLtMYOkcMrPZiCLmX81z5wosPk7Ug%3D&reserved=0) est renvoyé automatiquement vers [https://ckeditor.com/ckeditor-5/builder/](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fckeditor.com%2Fckeditor-5%2Fbuilder%2F&data=05%7C02%7Cclaude.sylvanie%40dauphine.psl.eu%7C7533be9e95a6403db33308dd1eac8fdb%7C81e7c4de26c94531b076b70e2d75966e%7C0%7C0%7C638700448682417044%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=kESiQ9XFlvbmEII%2BwW%2FOb73BGkewKZb4pQhdQkjbIVQ%3D&reserved=0) qui ne permet plus le téléchargement de la librairie en zip.

Pourriez-vous partager avec moi la procédure et les paliers techniques que vous utilisez lors d'une montée de version ESUP-Stage afin que je puisse la reproduire chez nous ?
M. Pierre GABRIELLE
Université Paris-Saclay

**Comment by Lucas-Thouvenot** [comment]
Bonjour M. Pierre GABRIELLE,

La mise à jour de CKEditor a été effectuée lors de la migration d'ESUP-Stage et sera disponible lors d'une prochaine release de l'application, ce qui devrait résoudre votre problème.

Si vous souhaitez l'intégrer vous-même dans l'application, vous pouvez vous rendre sur https://ckeditor.com/ckeditor-5/builder/ et suivre les étapes suivantes :

- Dans Presets, choisir le preset "Classic Editor (starter)" et cliquer sur "Next".

- Dans Features, choisir les fonctionnalités suivantes (* : obligatoire pour le bon fonctionnement minimal) :

  - Productivity : Find and Replace*, Special Characters*
  - File Management : Base64 Upload Adapter*
  - Text Formatting : Bold*, Italic, Underline, Strikethrough*, Subscript, Superscript, Font Styles, Remove Formatting*, Highlight*
  - Content & Block Formatting : Headings*, Links, Block Quotes*, Horizontal Line*, Indentation, Alignement*
  - Image : ImageInline, ImageBlock, ImageResize*, ImageUpload*, ImageStyle*, LinkImage, Image Insert Via Url, ImageCaption*, ImageTextAlternative
  - Lists : List*, ToDoList, ListProperties*
  - Tables : Table*, Table Properties*, TableCellProperties*, Table ColumnResize*, TableCaption
  - Advanced HTML Editing : SourceEditing*

Puis cliquer sur "Next".

- Dans Toolbar, laisser la toolbar par défaut et cliquer sur "Next".

- Dans Installation, sélectionner "Angular", puis "Self-hosted (npm)", et enfin "Copy code snippets". Pour finir, changer la langue en français.

Ensuite, vous pouvez supprimer le CKEditor déjà présent dans l'application, à cet emplacement : src/frontend/src/custom-ck5, et remplacer son implémentation dans les composants qui l'utilisent en suivant la documentation personnalisée de la page.
