### ISSUE TITLE
Type Structure manquante ?

### ISSUE THREAD

**Issue by ddelpire** [EsupPortail/esup-stage#3]
Dans la table TypeStructure, il manque l'id 99. 
A l'Université de Lille nous avons du l'ajouter en base alors que cette structure n'existe pas dans Pstage (après import Pstage).
Sans cet ajout nous avions une erreur dans le chargement du tableau de bord

**Comment by ssound** [comment]
Bonjour, nous n'avons pas non plus d'id 99 pour TypeStructure.
Si vous avez dû l'ajouter c'est que dans votre base de données il doit y avoir une Structure ou un StatutJuridique lié à l'idTypeStructure 99.

Je vous invite à exécuter la requête suivante pour vérifier votre base de données : 
`SELECT * FROM Structure WHERE idTypeStructure = 99`
`SELECT * FROM StatutJuridique WHERE idTypeStructure = 99`
