### ISSUE TITLE
CasLayer

### ISSUE THREAD

**Issue by lmartin59** [EsupPortail/esup-stage#4]
J'ai un soucis avec la partie Casification  de l'application:

le fichier CASLayer interroge le CAS pour vérifier le ticket mais attends une reponse en Json.  Or notre serveur CAS n'a pas l'air de savoir y répondre savez vous a partir de quelle version Cas réponds en Json?  et pourquoi ne pas utiliser la librairie java  CAS client 

De plus j'ai vu dans votre code 
  `casUser.setNumEtudiant(getStringValue(result.getJSONObject("serviceResponse").getJSONObject("authenticationSuccess").getJSONObject("attributes"), "uid"));`

Selon la norme SUPANN il existe un autre champs supannetuId pour le numéro étudiant  que le champs uid , surtout que nous n'utilisons pas le numéro étudiant comme uid danc ca ne fonctionnera pas chez nous .

**Comment by ssound** [comment]
La librairie spring-security-cas sera utilisée en 2.0.0 pour gérer à la fois le format json et xml : [701a10c](https://github.com/EsupPortail/esup-stage/commit/701a10cb7d84bc2e88c91762b140325cb4dd2adf)

Concernant les champs du LDAP, une mise à jour de esup-siscol sera mis à disposition pour pouvoir paramétrer les attributs.
