### ISSUE TITLE
fichier 1.0.0-convention-nomenclature.yaml

### ISSUE THREAD

**Issue by ddelpire** [EsupPortail/esup-stage#5]
Bonjour,

pouvez-vous passez le champ thème à 100 caractères, l'upgrade de base plante chez nous car notre champ est à 100 caractères car nous avons des intitulés qui dépassent 50 caractères.

**Comment by ssound** [comment]
Bonjour le champ theme sera passé à 255 caractères sur la version 1.0.5
https://github.com/EsupPortail/esup-stage/commit/7a0e42a8a3d7e99e07b26b3f4858559a49f1ff36
