### ISSUE TITLE
Problème d'authentification avec Esup-Stage v2.1.6

### ISSUE THREAD

**Issue by defre68** [EsupPortail/esup-stage#83]
Bonjour,

Ce matin, j'ai installé la mise à jour d'Esup-Stage 2.1.6 sur le serveur de test. Après l'authentification sur le CAS de l'Université, une fenêtre blanche apparaît avec le message suivant : 

"Whitelabel Error Page. This application has no explicit mapping for /error, so you are seeing this as a fallback. Wed Feb 07 11:40:30 CET 2024. There was an unexpected error (type=Internal Server Error, status=500)."

Dans les logs catalina, il y a ceci :

11:28:09.478 [https-jsse-nio-8443-exec-2] DEBUG org.springframework.security.web.FilterChainProxy - Secured GET /ldap/bySupannAliasLogin?login=frederic.roger%2540uha.fr

11:28:09.590 [https-jsse-nio-8443-exec-2] INFO org.esupportail.referentiel.ldap.services.PersonServiceMapperMethod - La recherche n'a pas trouvé de résultat pour frederic.roger%40uha.fr DN ou=people

L'identifiant de connexion à l'Université de Haute-Alsace est de la forme prenom.nom@uha.fr. Jusqu'alors, la version précédente d'Esup-stage permettait de se connecter sans problème. En remontant plus loin dans les logs catalina.out, lorsque l'application était dans la version précédente, il semble que le problème vienne de la transformation du @ en %2540. L'ancienne version d'Esup-Stage le transformait uniquement en %40, ce qui permettait la connexion.

Merci,

Bien cordialement,

Frédéric ROGER

**Comment by ssound** [comment]
À corriger

**Comment by csylvanie** [comment]
Difficile de corriger/tester car je ne reproduis pas le souci.

J'ai néanmoins modifié le code pour que ce soit l'uriBuilder qui ajoute les query params.

À contrôler en téléchargeant les sources via la branche dev et en déployant l'application dans un environnement de qualification.

**Comment by csylvanie** [comment]
Corrigé dans la version 2.1.8
